export default {routes:[
{
path:'Basic',
name:'Basic',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/Basic/index.js')
},
{
path:'Home',
name:'Home',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/Home/index.js')
},
{
path:'Task/Historical/Add',
name:'Task-Historical-Add',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/Task/Historical/Add/index.js')
},
{
path:'Task/Historical/List',
name:'Task-Historical-List',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/Task/Historical/List/index.js')
},
{
path:'Task/Historical',
name:'Task-Historical',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/Task/Historical/index.js')
},
{
path:'Task/Ongoing/Home',
name:'Task-Ongoing-Home',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/Task/Ongoing/Home/index.js')
},
{
path:'Task/Ongoing/List',
name:'Task-Ongoing-List',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/Task/Ongoing/List/index.js')
},
{
path:'Task/Ongoing',
name:'Task-Ongoing',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/Task/Ongoing/index.js')
},
{
path:'Task/Unfinished/Home',
name:'Task-Unfinished-Home',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/Task/Unfinished/Home/index.js')
},
{
path:'Task/Unfinished/List',
name:'Task-Unfinished-List',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/Task/Unfinished/List/index.js')
},
{
path:'Task/Unfinished',
name:'Task-Unfinished',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/Task/Unfinished/index.js')
},
{
path:'Task',
name:'Task',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/Task/index.js')
},
{
path:'/',
name:'-',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/index.js')
},
{
path:'planning/home',
name:'planning-home',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/planning/home/index.js')
},
{
path:'planning',
name:'planning',
component:()=>import('/Users/songkk/kr-dev/Code/xunlian/krReact/src/pages/planning/index.js')
},]}